version: '3.7'

services:
  api:
    container_name: userlist-api
    build: .
    env_file:
      - .env

  postgres:
    container_name: userlist-postgres
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
